prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF

.storybook/preview.ts, package-lock.json, package.json, src/components/ErrorText.tsx, src/components/Input.tsx, src/index.css, src/pages/SignupPage.tsx, src/stories/Button.tsx, src/stories/ErrorText.stories.tsx, src/stories/Input.stories.tsx, tailwind.config.js
- close #10 
1. daisy ui, react icons 설치
2. signup 페이지 컴포넌트 이름 변경
3. 폰트, 색상 설정 추가
- 사용법
```
<p className='font-Cafe24Surround bg-input-white text-cooled-blue'><p>
```
=> design : Input, Errortext 컴포넌트 생성 및 추가 작업

vercel.json
#13 
- 404에러를 해결하기 위해 vercel.json을 추가했습니다.
=> fix: vercel.json 추가

src/App.tsx, src/pages/SignupPage.tsx
- close #이슈번호
1. 리액트 쿼리 useMutation을 사용하여 상태관리를 해보았습니다.
2. 리액트 훅폼을 사용하여 유효성 체크를 해보았습니다.
https://github.com/prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF/assets/104294861/fd02c38a-5a37-406e-82fb-58e9ef11f354
1. App.tsx에서 QueryClientProvider 처리를 할 필요가 있을까요...?
2. 상태관리를 어떻게 분리하면 좋을지 모르겠어서 일단 SignupPage페이지에 다 넣었는데ㅠㅠㅠ어떤식으로 분리하면 좋을지 궁금합니다!
3. 폼 제출할때 유효성체크하는 것보다는 제출하기전에 유효성 체크를 하면 좋을것같아 mode를 all로 설정했는데 맞게 한건지 궁금합니다!
=> feat: 회원가입 구현

src/App.tsx, src/api/auth.ts, src/api/axiosClient.ts, src/api/signUp.ts, src/components/Loader.tsx, src/context/AuthContext.tsx, src/hooks/useAuthContext.tsx, src/hooks/useSignUp.tsx, src/pages/SignupPage.tsx, src/types/Channel.ts, src/types/Comment.ts, src/types/Conversation.ts, src/types/Follow.ts, src/types/Like.ts, src/types/Message.ts, src/types/Notification.ts, src/types/Post.ts, src/types/User.ts, src/types/signUp.ts, src/utils/Router.tsx, src/utils/localStorage.ts
- close #16 
회원가입 기능을 구현했습니다
- 회원가입 validation
- 회원가입 성공시 메인 화면으로 라우팅
- 에러시 alert
회원가입 성공시 response 정보는 다음과 같이 저장합니다
- localStorage에 accessToken저장
- Context에 User 정보 저장
- App이 처음 실행될때 서버에서 로그인된 User를 fetch하는 기능도 추가했습니다
1. validation
2. error
3. 성공
react query의 onError를 이용해서 axios error를 잡으려고 했는데 onError함수가 실행됨에도 불구하고 별개로 axios error가 출력됩니다...
원인을 모르겠는데 같이 고민해보면 좋겠습니다.
=> feat : 회원가입 기능

package-lock.json, package.json
=> chore: react-error-boundary 설치

.commitlintrc.json, .config/cz-config.js, .husky/pre-push, .storybook/preview.ts, package-lock.json, package.json, src/components/ErrorText.tsx, src/components/Input.tsx, src/index.css, src/pages/SignupPage.tsx, src/stories/Button.tsx, src/stories/ErrorText.stories.tsx, src/stories/Input.stories.tsx, tailwind.config.js, vercel.json
- close #이슈번호
- useForm과 SubmitHandler를 통해 각 input의 data를 등록하고 관리합니다.
- useMutation으로 데이터를 생성하고 업데이트 합니다. useQuery로 데이터를 불러옵니다. 
- 다른 분들의 pr, 코드리뷰, 공식문서 등을 참고하여 작성하였습니다. 
- 코드를 보는 것보다 '얘가 공부를 하고 있긴 하구나' 하고 생각하시고 확인만 해주시면 될 것 같습니다.
=> study: 회원가입 기능 스터디

src/pages/SignupPage.tsx
- close #
- 라이브러리가 아직 어색하네요 ㅎㅎ... 개선점이 있다면 말씀 부탁드립니다! 바로 피드백 반영하겠습니다.
=> feat: 회원가입 페이지 추가

src/components/MainButton.tsx
- close #37 
- getModeClasses 함수 제거, modeClasses 객체로 변경
- useMemo 훅 제거
=> refactor: modeClasses 함수에서 객체로 변경

src/components/BackButton.tsx, src/components/CloseButton.tsx, src/stories/BackButton.stories.tsx, src/stories/CloseButton.stories.tsx
- close #24 
닫기 버튼과 뒤로가기 버튼 컴포넌트를 만들었습니다.
- CloseButton
- BackButton
- 동호님 코드 살짝 편집해서 썼습니다. tailwind와 react-icons 사용 등 복잡하진 않지만 새로운 걸 한꺼번에 접하다보니 공부하느라 좀 늦게 구현했습니다! 
- 사이즈는 피그마 px 기준으로 rem으로 변환하여 만들었습니다.
- BackButton 컴포넌트는 동일한 크기로 쓰일 것 같아 따로 옵션?(크기, 색상 등등)은 지정해주지 않았는데, 의견에 따라 size를 수정 가능하게 해도 좋을 것 같습니다. 
- 닫기 large 버튼, 뒤로가기 버튼은 'tricorn-black' 색상으로, 닫기 small 버튼은 `lazy-gray' 색상으로 변경하였습니다.
- 불필요한 속성 등은 제거하였습니다.
=> feat: CloseButton, BackButton 컴포넌트 구현

src/components/HeaderText.tsx
- close #57 
- HeaderText 공통 컴포넌트 props 타입을 수정했습니다.
=> fix: HeaderText 공통 컴포넌트 props 타입 수정

src/components/BackButton.tsx, src/components/CloseButton.tsx, src/components/Comment.tsx, src/stories/Comment.stories.tsx
- close #44 
Comment 공통 컴포넌트를 구현했습니다. 
- active: true일 시 자신의 댓글을 의미하는 것으로 삭제하는 버튼이 보입니다. 
-  CloseButton, BackButton 컴포넌트에서 cursor-pointer를 설정해주었습니다. 
- 댓글의 아바타 혹은 닉네임에 cursor-pointer를 설정해주었습니다. 
- 날짜 폰트가 피그마 상에서 다른 폰트로 적용되어 있던데...우선은 cafe24surround 폰트로 적용했습니다.
- 피그마 기준으로 댓글 텍스트 색상 설정했는데 tricorn black으로 바꿀까요?
- 구분선 공통 컴포넌트를 만들면 좋겠다고 생각했습니다... 제가 만들어도 되고요!
=> design: Comment 공통 컴포넌트 추가

src/components/Article.tsx, src/components/Tab.tsx, src/stories/Tab.stories.tsx, src/utils/getTimeDelta.ts
=> refactor: Tab, Article 공통 컴포넌트 수정

src/api/auth.ts
- close #69 
- `/api/auth.ts` 사용자 인증 api에서 로컬 스토리지 token을 파싱하는 부분 추가
=> fix: auth에 json parsing 추가

src/pages/SearchPage.tsx
검색 페이지 스터디를 했습니다. 
- 검색창에 입력된 값이 바뀔 때마다 useEffect를 사용하여 타이머를 설정하고 1000ms 후에 디바운스된 입력값을 업데이트 합니다. 
- useQuery로 디바운스된 입력값을 검색합니다. 
- 지금 윈도우 화면 녹화가 안 되네요...?
- 검색창에 입력된 값을 1000ms 후에 저장하는 값이 있으면 좋겠다고 생각하고 구현한 건데 디바운스를 이렇게 하는 게 맞는지 궁금합니다.
=> feat: 검색페이지 스터디 with debounce

src/api/search.ts, src/hooks/useDebounce.tsx, src/pages/SearchPage.tsx, src/types/Comment.ts, src/types/Like.ts, src/types/Message.ts, src/types/Post.ts, src/types/User.ts
- close #이슈번호
검색페이지를 구현해 보았습니다
- 디바운스를 이용했습니다.
- input이 비어있을때 빈 배열을 반환하도록 했습니다.
- isLoading을 이용해서 로딩화면을 만들어 봤는데
- input이 비어있을땐 promise의 성공을 캐치 못하는 것 같습니다. 보완해보겠습니다
- 로딩 시간에 따라 스켈레톤 ui를 보여주는 건 이 글을 참고해보면 좋을 것 같습니다.
https://tech.kakaopay.com/post/skeleton-ui-idea/
=> feat: 검색 기능 구현

src/components/FormInput.tsx, src/pages/NewArticlePage.tsx, src/pages/SearchPage.tsx
- 게시글 작성 기능에 충실해보았습니다
- 하다가 너무 안 돼서 창욱 님 걸로 공부했습니다
=> feat: 글 작성 페이지 스터디 

src/api/search.ts, src/hooks/useDebounce.tsx, src/pages/NewArticlePage.tsx, src/pages/SearchPage.tsx, src/types/Comment.ts, src/types/Like.ts, src/types/Message.ts, src/types/Post.ts, src/types/User.ts
- 글 작성 페이지를 구현해보았습니다
- 글 작성에 성공하면 4초동안 성공했다는 알림을 보여줍니다
- 이미지를 업로드하면 미리보기를 보여주었습니다
- 제목 validation은 trigger와 onchange모드를 이용해 글자가 변할때마다 validation이 동작하도록 했습니다
=> feat : 글 작성 페이지 스터디

src/components/Article.tsx, src/components/FormInput.tsx, src/components/MainButton.tsx, src/components/Tab.tsx, src/hooks/useSignUp.tsx, src/pages/SignupPage.tsx, src/stories/Tab.stories.tsx, src/utils/getTimeDelta.ts
- close #62 
- 회원가입 페이지들의 요소들을 컴포넌트로 교체했습니다 (HeaderText, Mainbutton)
- 로그인페이지로 가는 링크를 추가했습니다
cherry-pick으로
메인 브랜치에서 54887c3  커밋 가져왔는데 혹시 문제 되는 부분 있는지 봐주세요
=> Feat : 회원가입 기초 레이아웃

src/stories/Article.stories.tsx
- close #82 
Article 공통 컴포넌트 storybook 오류 수정하였습니다.
=> fix: article 공통 컴포넌트 storybook 오류 수정

src/components/Article.tsx, src/components/BottomNavigation.tsx, src/constants/Article.ts, src/constants/BottomNavigation.ts, src/hooks/useArticles.tsx, src/hooks/useFilteredArticles.tsx, src/pages/ArticlesPage.tsx, src/stories/BottomNavigation.stories.tsx, src/stories/Tab.stories.tsx
- close #54 
하단 고정 네비게이션 바를 만들었습니다. 
- 하단 탭을 누르면 해당 페이지로 이동합니다.
- 하단 바를 사용하는 페이지에서 prop으로 페이지 경로를 string으로 넘겨주면 됩니다. 
ex) `currentPage='/home'`, `currentPage='/notification'`
=> design/BottomNavigation 공통 컴포넌트 구현

src/components/SubButton.tsx, src/stories/SubButton.stories.tsx
- close #94 
1. 컴포넌트 명 SubOutlineButton => SubButton으로 변경했습니다.
2. 클래스명 상수로 변경했습니다.
3. children을 label로 변경했습니다.
4. width랑 height를 size로 변경하였습니다. => 피그마랑 사이즈 비슷하게 했는데 확인해주세용!
5. 데이지 ui를 사용했습니다.
차례대로 ` 'small' | 'medium' | 'large'`
해당 컴포넌트를 단독으로 사용할시 저런 오류가 발생하는데
```
const LandingPage = () => {
return (
<div>
<SubButton label="test" color="red" type="outline" />
</div>
);
};
```
다른 태그 또는 컴포넌트와 같이 사용했을때에는 저런 문제가 발생하지 않습니다.
해당 오류에 대해서는 좀 더 찾아봐야할것같습니다. 요건 이슈로 남겨놓겠습니다! -#100 
아시는 분께는 도움 요청 드려봅니다. 😭
=> refactor: subButton 컴포넌트 코드 수정

src/components/BottomNavigation.tsx, src/stories/BottomNavigation.stories.tsx
- close #106 
- BottomNavigation 컴포넌트의 storybook react-router-dom 에러를 해결하였습니다.
- 현재 선택된 페이지에 따라 탭 색상이 변경되도록 수정했습니다.
- fixed bottom-0 속성을 제거하였습니다.
=> fix: BottomNavigation 컴포넌트 storybook error 해결

src/components/TabItem.tsx
- close #113 
type TabItemProps {...} 부분을 수정하였습니다.
=> fix: TabItem type 선언 오류 해결

src/components/Toast.tsx, src/stories/Toast.stories.tsx, tailwind.config.js
- close #84 
- Toast 메시지 UI 컴포넌트 구현
```tsx
const SUCCESS_MESSAGE = '로그인에 성공했습니다.';
<Toast mode="success">{SUCCESS_MESSAGE}</Toast>
```
```tsx
<Toast onClick={handleToastClick}>여기 좀 보세요!<br />눌러 좀 보시라니까요?</Toast>
```
- children을 받아서 사용하도록 되어 있습니다. (줄바꿈 문제로 인해)
- `<br />` 태그를 통해 줄바꿈이 가능합니다.
- mode 프롭스는 **'info' | 'success' | 'error'** 세 가지 타입이 존재합니다.
- default 값은 'info' 입니다.
- mode 타입에 따라 토스트의 색상 테마가 변경됩니다.
<div align="center">
**[info 타입]**
**[success 타입]**
**[error 타입]**
</div>
- 프로젝트 전반에 사용하기 위해서는 context API, custom hook 등이 필요할 것으로 생각됩니다.
=> design: Toast 공통 컴포넌트 구현

src/components/Article.tsx, src/index.css, tailwind.config.js
- Article 공통 컴포넌트의 폰트 사이즈 수정
- timestamp와 nickname의 폰트 사이즈를 모두 0.75rem(12px)으로 수정
=> fix: 아티클 폰트 사이즈 수정

src/pages/LandingPage.tsx
- 랜딩 페이지의 캐치프레이즈에 줄바꿈이 적용되지 않는 문제 해결
- 랜딩 페이지에 user-select:none 적용
=> fix: 캐치프레이즈 줄바꿈 수정

src/App.tsx
- 개발 과정에서 사용할 간단한 navbar 추가
- 제거 필요시 App 최상위 컴포넌트에서 TempNavBar 컴포넌트를 제거하고 개발하세요.
<div align="center">
**[임시 navbar UI]**
</div>
=> feat: 임시 navbar 추가

src/components/Comment.tsx, src/hooks/useArticleDetail.tsx, src/pages/ArticleDetailPage.tsx, src/pages/ArticleDetailPage/CommentInput.tsx, src/pages/ArticleDetailPage/Comments.tsx
@/type
위와 같이 되어 있던 파일 경로를
@/type
이렇게 수정하였습니다.
=> refactor: 파일경로 수정

index.html
- close #135 
- index.html에 메타데이터를 추가했습니다
=> feat: 메타 데이터 추가

src/components/BottomNavigation.tsx, src/pages/NotificationPage.tsx
- close #123 
하단 네비게이션 리팩토링을 수행했습니다.
- 로그인 시 자신의 프로필 페이지를 보여줍니다.
- 로그인을 하지 않았다면 로그인 페이지로 이동합니다.
=> refactor: 네비게이션 프로필 버튼 수정 + 알림 페이지 오타 수정

src/hooks/useArticleDetail.tsx
- close #137 
useArticleDetail 훅을 수정했습니다.
=> fix: useArticleDetail 커스텀 훅 수정

src/components/SubButton.tsx
- close #141 
서브 컴포넌트 다크모드 추가하고 border 스타일을 간단하게 수정했습니다.
=> refactor : SubButton 컴포넌트 다크모드 

src/api/axiosClient.ts, src/api/common/User.ts, src/api/common/UserSettings.ts, src/components/BottomNavigation.tsx, src/components/MainButton.tsx, src/hooks/useEditProfile.tsx, src/pages/LandingPage.tsx, src/pages/ProfileEditPage.tsx, src/pages/ProfileEditPage/EditForm.tsx
- close #122 
- 이미지 변경 기능을 추가했습니다
- 회원정보를 변경하지 않고 수정버튼을 누를시 기존 정보와 같다는 알림을 보여주었습니다.
- axios Instance의 request time을 7초로 늘렸습니다(고화질 사진 보내는 시간)
=> feat:  프로필 수정 페이지 수정

public/favicon/manifest.json, src/constants/Messages.ts, src/hooks/useArticle.tsx, src/hooks/useArticleDetail.tsx, src/hooks/useAuthQuery.tsx, src/hooks/useChangePassword.tsx, src/hooks/useEditProfile.tsx, src/pages/ProtectedRouter.tsx
- close #163 
- 토스트 메시지가 적용되었습니다.
- 다크모드를 적용해야겠습닏..
=> feat: 토스트 메시지 일괄 적용

src/App.tsx, src/index.css, src/pages/LandingPage.tsx, src/pages/NotificationPage.tsx, src/pages/ProfileEditPage.tsx, src/pages/SignupPage.tsx
- close #167 
- index.css에서 다크모드일때 body의 배경색 설정
- 회원가입, 알림 페이지 레이아웃 수정
- 좌측에 있던 임시 네비게이션 바 삭제
- 랜딩 페이지에 있던 bg-white제거
=> design: 회원가입, 알림 페이지 레이아웃 수정, 다크모드일때 body 배경색 추가

src/pages/LandingPage.tsx, src/pages/LoginPage.tsx, src/pages/NotFoundPage.tsx
- close #177 
- index.css 전역 스타일에서 배경 색을 지정해주니, 그 부분은 제하고 작성했습니다.
- 추가사항으로 로그인 페이지의 헤더 텍스트 위치를 왼쪽으로 변경했습니다.
=> design: 랜딩, 로그인, 404 페이지 다크모드 추가

src/pages/ArticleDetailPage.tsx, src/pages/ArticleDetailPage/CommentInput.tsx, src/pages/HomePage.tsx, src/pages/NewArticlePage.tsx
- close #180 
이슈에 작성한 내용을 수정하였습니다. 
고쳐야지, 생각하고 fix라고 했는데 다시 생각해보니 design이 맞을 것 같습니다.. 혼선 드려 죄송합니다!
=> design: 글 상세, 글 수정 페이지에서 다크모드시 오류

src/pages/ProfilePage.tsx
- close #182 
- 프로필 페이지에서 사진 저장하도록 수정했습니다.
- 톱니바퀴모양 아이콘을 추가했습니다.
- 일단 프로필 수정 페이지로 이동하도록 했습니다.
=> refactor: 프로필 페이지에서 사진 저장하도록 수정 + 톱니바퀴모양 버튼 추가(프로필 수정 페이지로 이동)

src/components/SearchResultList.tsx, src/components/SubButton.tsx, src/components/UserListItem.tsx, src/hooks/useFollowQuery.tsx, src/pages/HomePage.tsx, src/pages/SearchPage.tsx, src/stories/SubButton.stories.tsx
- close #165
팔로우, 언팔로우 낙관적 업데이트 와 서브버튼 컴포넌트 디자인을 수정하였습니다
https://github.com/prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF/assets/104294861/660a80e3-04b5-4634-8474-3db0d18bc8f9
https://github.com/prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF/assets/104294861/6bb0edca-3f83-4954-acf7-48ab40e590ee
=> refactor : search page 디자인 수정 + 팔로우 바로 반영

src/components/FormInput.tsx, src/components/SubscribeInfo.tsx, src/constants/Messages.ts, src/pages/ChangePasswordPage.tsx, src/pages/ProfileEditPage/EditForm.tsx
- close #190 
- 비밀번호 변경 페이지 변경 시 모달 추가
- 비밀번호 변경 페이지 버튼 추가
- 각종 다크모드 추가
=> feat: 비밀번호 변경 페이지 모달 및 버튼 추가 + 다크모드 적용

src/components/Article.tsx, src/components/Comment.tsx, src/constants/Article.ts, src/index.css, src/pages/ArticleDetailPage.tsx, src/pages/ArticleDetailPage/CommentInput.tsx, src/pages/ArticlesPage.tsx, src/pages/ArticlesPage/Articles.tsx, src/pages/HomePage.tsx, src/pages/NewArticlePage.tsx, src/pages/ProfilePage.tsx, src/pages/SearchPage.tsx, tailwind.config.js
=> design: 다크모드 및 버그 수정

src/pages/HomePage.tsx, src/pages/HomePage/HotArticles.tsx, src/pages/NotificationPage.tsx, tailwind.config.js
- close #185
뜨거운 뉴스가 비어 있을 때의 화면을 추가했습니다
=> feat: hot 게시글이 비어있을 때 화면

src/components/ArticleInfoIcon.tsx, src/components/SubButton.tsx, src/hooks/useArticleDetail.tsx, src/hooks/useLikeCreateMutation.ts, src/hooks/useLikeDeleteMutation.ts, src/pages/ArticleDetailPage.tsx
- close #175 
- 좋아요 누르기, 좋아요 취소하기에 대해 useMutation을 사용하여 연속 클릭과 낙관적 업데이트가 가능하도록 하였습니다. 
- 응원하기 버튼에 아이콘을 넣었습니다. 
- 응원하기 버튼을 누르면 게시물의 좋아요수를 표시하는 아이콘도 색상이 변화합니다. 
invalidqueries를 이렇게 써도 되는지 궁금합니다.
=> refactor: 좋아요 기능 리팩토링

src/api/saveArticle.ts, src/components/Avatar.tsx, src/components/MainButton.tsx, src/constants/Messages.ts, src/hooks/useArticle.tsx, src/hooks/useAuthQuery.tsx, src/hooks/useChangePassword.tsx, src/hooks/useEdit.tsx, src/hooks/useEditProfile.tsx, src/pages/ArticleDetailPage.tsx, src/pages/ArticleEditPage.tsx, src/pages/ArticleEditPage/ArticleEditForm.tsx, src/pages/ArticlesPage.tsx, src/pages/HomePage.tsx, src/pages/NewArticlePage.tsx, src/pages/ProfilePage.tsx, src/pages/index.ts, src/type/User.ts, src/utils/Router.tsx, src/utils/safeJSONParse.ts
- close #162
- 글 수정 페이지를 구현했습니다.
- 기존 공통 컴포넌트들에서 생기는 타입 오류를 수정하기 위해 공통 컴포넌트들의 타입을 변경했습니다.
- 오타를 수정했습니다.
- useEdit 훅을 추가했습니다.
- BottomNavigation이 고정된 상태로 존재하도록 수정했습니다. 
- title을 JSON.parse하는 util 함수를 추가했습니다.
=> feat: 글 수정 페이지 추가 + 레이아웃 수정

src/pages/NewArticlePage.tsx
- close #194 
게시글 작성 시 선택한 말머리는 글 작성 후 제출 시 제목에 붙어서 보내집니다.
=> feat: 글 작성 시 option 입력을 제목에서 빼기

src/hooks/useArticleDetail.tsx, src/hooks/useLikeMutation.ts, src/pages/ArticleDetailPage/CommentInput.tsx
- close #211 
- 좋아요, 댓글 작성 시 게시글을 새로 받아오도록 수정했습니다.
=> refactor: 좋아요, 댓글 작성 시 게시글 새로 받아오도록 수정 (구독한 탭은 추후 수정 예정)

src/pages/ArticleDetailPage.tsx, src/pages/ArticleEditPage/ArticleEditForm.tsx
- close #215 
좋아요 취소 누를 시 알림 가던 문제를 해결했습니다. 
왜... 거기다 알림을 달아놨는지는 모르겠습니다. 졸려서 그랬나봅니다!!!!
=> fix: 좋아요 취소 누를 시 알림 가던 문제 해결

src/components/BottomNavigation.tsx, src/hooks/useNotificationQuery.tsx, src/pages/ArticleEditPage/ArticleEditForm.tsx
- close #208
- 네비게이션 바에 알림 뱃지를 추가했습니다
알림 뱃지의 크기나 애니메이션에 더 좋은 의견 있으면 남겨주세요!
=> feat: 네비게이션 바에 알림 뱃지 추가

src/hooks/useArticle.tsx, src/hooks/useArticleDetail.tsx, src/pages/ArticleDetailPage.tsx, src/pages/ArticleEditPage/ArticleEditForm.tsx
- close #223 
- 글 삭제 시 모달창이 뜹니다 
- 글 생성 및 삭제 시 게시글이 갱신됩니다.
=> refactor: 게시물 삭제 시 모달, 생성삭제 시 게시글 갱신

src/pages/ArticleDetailPage.tsx
=> fix: 핫픽스 import 오류

src/components/BottomNavigation.tsx
=> fix: 네비게이션 바 알림 뱃지 디자인 수정

src/components/DarkMode.tsx, src/pages/HomePage.tsx, tailwind.config.js
- close #222 
- 홈 화면에서 검색 키 대신 다크모드 버튼이 생겼습니다. 
- 다크모드, 라이트모드 변경 가능
=> feat: 다크모드 버튼 홈 화면에 추가

src/components/BottomNavigation.tsx, src/constants/Messages.ts, src/pages/NotificationPage.tsx, src/pages/NotificationPage/NoticeList.tsx, src/pages/ProfileEditPage/EditForm.tsx, src/pages/ProfilePage.tsx
- close #235 
알림 페이지
ui쪽으로 애매한 것 같습니다... 수정할 부분 나중에 알려주시면 다음 pr때 반영하겠습니다
=> feat : 알림 페이지 필터

src/pages/ArticlesPage/RenderFollowingArticles.tsx
- 머지 컨플릭트 해결 후 import 구문 에러 수정
=> fix: import 구문 에러 수정

src/pages/NotificationPage.tsx
- close #247 
- 알림 페이지 필터 버튼 UI 디자인 수정
- 헤더텍스트와 필터 버튼이 속한 요소 레이아웃 수정
- 필터의 타입 '안 읽음'을 '새 알람'으로 수정
=> design: notification page filter ui 수정

src/constants/Article.ts
=> hotfix: 채널아이디 변경

src/index.css, src/pages/ArticleDetailPage.tsx, src/pages/ArticleEditPage.tsx, src/pages/ArticlesPage.tsx, src/pages/HomePage.tsx, src/pages/NewArticlePage.tsx, src/pages/NotificationPage.tsx, src/pages/NotificationPage/NoticeList.tsx, src/pages/ProfilePage.tsx, src/pages/SearchPage.tsx
- close #256 
- 알림, 글 상세, 글 작성, 글 수정, 프로필, 검색 페이지 레이아웃 수정
- 이제 더 이상 가로 스크롤 바가 생기지 않음
=> design: 대부분 페이지 레이아웃 수정 완료

.github/workflows/chromatic.yml, .storybook/preview-body.html, package-lock.json, package.json, src/components/ArticleDetail.tsx, src/pages/ArticlesPage/RenderFollowingArticles.tsx, src/stories/ArticleDetail.stories.tsx, src/stories/BottomNavigation.stories.tsx, src/stories/Comment.stories.tsx, src/stories/Toast.stories.tsx
- close #232 
- 스토리북을 크로마틱으로 배포하도록 했습니다
- CI/CD가 가능하도록 github action을 추가했습니다
- storytbook발생한 에러를 수정했습니다 (라우터, 쿼리, 컨텍스트 프로바이더로 감쌈)
=> chore : storybook 크로마틱으로 재배포

src/pages/HomePage.tsx, src/pages/SearchPage/UserListItem.tsx
- close #265
홈화면에서 초록색 배경이 따라오는걸 수정했습니다.
홈화면에서 뜨거운뉴스 옆에 불 아이콘 을 추가했습니다.
=> refactor: 홈화면 css수정+팔로우 버튼클릭시 토스트 타입변경

src/hooks/useAuthQuery.tsx, src/hooks/useFollowQuery.tsx, src/pages/ArticlesPage/RenderFollowingArticles.tsx
- close #274 
- close #273 
- close #272 
이슈의 오류들을 수정했습니다.
=> fix: 로그아웃 시 캐시 삭제 + 커스텀 훅 쿼리키 수정 + 구독한 탭 스켈레톤 오류 수정

.github/workflows/chromatic.yml, .husky/pre-push
- close #232
깃허브 액션 스크립트를 수정했습니다
=> chore : 깃허브 액션 스크립트 수정 282

.github/workflows/build-test.yml
- close #285 
PR에 올라갈 때와 main에 PR이 머지될떼 빌드 테스트를 진행하도록 깃허브 액션을 설정하였습니다
=> chore : 빌드 테스트 깃허브 액션 추가

src/pages/ArticlesPage/RenderFollowingArticles.tsx
- close #290 
이슈를 수정했습니다.
- 로그인을 하지 않은 회원이면 로그인 페이지로 이동시켰습니다.
=> fix: 구독한 탭에서 네트워크 요청 전에 텍스트 나오는 현상 수정

src/App.tsx, src/components/DarkModeButton.tsx, src/context/DarkModeContext.tsx, src/hooks/useThemeContext.tsx, src/main.tsx, src/pages/HomePage.tsx
- close #276 
처음 앱에 들어갔을 때 다크모드를 불러오지 못하는 버그를 수정하였습니다
=> fix: 다크 모드 버그 수정

src/pages/ArticleDetailPage.tsx
- 글 상세에서 댓글 끝가지 안 내려지던 거 수정
- 글 상세에서 이미지에 alt추가
=> hotFix/article detail 댓글 내리기, 이미지 alt

index.html
=> chore : update meta tag

src/index.css
- close #301 
- `font-display: swap`을 적용했습니다.
- SignUpPage의 이름 대소문자를 변경했습니다.
=> feat: 웹 폰트 렌더링 방식 변경

src/pages/ArticlesPage/RenderFollowingArticles.tsx
- close #303 
구독한 탭 스켈레톤 오류를 수정했습니다.
=> fix: 구독한 탭 스켈레톤이 안보이고 로더만 보이는 이슈 수정

src/pages/ArticleDetailPage.tsx
- close #305 
- 글 상세 페이지 articleBody에 줄바꿈이 적용되도록 수정
<div align="center">
**[적용 전]**
**[적용 후]**
</div>
=> fix: 글 상세 페이지 공백 처리 방식 변경

.eslintrc.json, package-lock.json, package.json, public/mockServiceWorker.js, src/main.tsx, src/utils/getKeyByValue.spec.ts, src/utils/getKeyByValue.ts, src/utils/test/render.tsx, src/utils/test/setupTests.ts, tsconfig.json, vite.config.ts
- close #320
- 테스트를 위해 초기 세팅을 진행했습니다
- 예제 단위 테스트를 추가했습니다
- msw 는  설치는 해놓았는데 아직 mock api를 만들지 않았기 때문에 서비스워커가 동작하는 코드는 넣지 않았습니다.
=> chore: test 환경 초기 세팅

.github/workflows/build-test.yml, .github/workflows/chromatic.yml, src/components/ErrorText.tsx
=> fix: 크로마틱 테스트 및 깃허브 액션 스크립트 변경

src/utils/getTimeDelta.ts
- close #339 
작성 시간이 60초 이하일 경우, <strong>`-x초 전`</strong>을 <strong>`방금 전`</strong>으로 표시하도록 수정
* 표시 방법을 변경
=> refactor: 1분 이전에 작성된 글은 '방금 전'으로 표시되도록 수정
