prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF

- src/components/MainButton.tsx
- src/stories/MainButton.stories.tsx
- close #17 
스타일 입힌 메인 버튼 컴포넌트입니다.
hover 스타일이 추가되어 있습니다. (확인해주세요.)
- (이슈-브랜치생성-커밋-푸시-PR 하는데 30분 넘게 걸린 듯 합니다. 엄청 헤맸네요.)
- 사이즈를 정확한 px로 하고 있습니다.
- 버튼의 `label`을 프롭으로 받고 있습니다.
- 기존 html 버튼 태그는 `<button>버튼라벨</button>`식으로 했지만, `<MainButton label="버튼라벨" />` 이렇게 해야 합니다.
- `block` 요소로 정해뒀는데, 혹시 `inline-block`이 필요할 가능성이 있을까요?
- px에서 rem으로 수정했습니다. rounded는 tailwind에서 제공하는 사이즈 (`md`)로 했습니다.
> feat: MainButton 공통 컴포넌트 추가

- src/components/ArticleInfoIcon.tsx
- src/stories/ArticleInfoIcon.stories.tsx
- close #36 
- 응원하기 아이콘, 댓글 아이콘 컴포넌트를 구현했습니다. 
- 'list'는 게시물 목록에서 보여질 때, 'post'는 글 상세 페이지에서 보여질 때입니다. 
- 해당 게시물의 id를 받는 prop을 만들어야 할까 고민하다가 우선 컴포넌트 디자인만 구현하는 거라서 뺐습니다. 
- Post 모델을 보니까 likes와 comments는 배열 길이로 받아줘야 하는 것 같은데 맞나요?
> design: article-info-icon 공통 컴포넌트 구현

- src/api/auth.ts
- src/components/FormInput.tsx
- src/context/AuthContext.tsx
- src/hooks/useSignUp.tsx
- src/pages/SignupPage.tsx
- close #28 
- 회원가입에서 사용하는 메시지를 상수로 분리했습니다
- 비밀번호를 보여주는 토글 버튼을 추가했습니다
- 토글 버튼은 비밀번호 또는 비밀번호 확인 값이 입력됐을 때만 보입니다
- user를 fetch받는 부분에서 발생하는 버그를 수정했습니다
FormInput에 너무 많은 값을 주입하는 것 같네요 ㅎㅎ...
나중에 구조를 수정하려합니다
> Feat: 비밀번호 보여주는 토글버튼 추가

- src/api/login.ts
- src/hooks/useLogin.tsx
- src/pages/LoginPage.tsx
- close #68 
- **기능/로그인하기**
- 인증된 사용자는 로그인을 할 수 있습니다.
- 로그인에 성공하면 홈으로 리다이렉션
- 로그인에 실패하면 alert (useLogin 훅)
- **구현된 UI**
- 이메일 입력 칸
- 비밀번호 입력 칸
- 로그인 버튼
- 회원가입 버튼
- (추가됨) 홈으로 가기 버튼
[로그인 실패 시]
[로그인 성공 시]
- 기능 이외 레이아웃 디자인 수정이 필요합니다.
- SignUp 페이지의 코드와 거의 흡사하기에 공통 부분을 묶어서 분리해야 할 것 같습니다.
- 로그인 성공 및 실패에 대한 피드백을 현재는 alert로 처리해두었는데, 이 부분을 어떻게 처리할 지 고민해야 합니다.
> feat: 로그인하기

- src/pages/ProfileEditPage.tsx
- src/pages/ProfileEditPage/EditForm.tsx
- src/pages/index.ts
- src/utils/Router.tsx
- close #98 
- 이슈대로 프로필 수정 페이지 레이아웃을 추가했습니다.
- 프로필 수정 페이지의 url이 없어서 /profile/edit으로 설정해놓았습니다
게시글 작성, 프로필 수정등의 input, validation이 비슷한 것 같은데 컴포넌트로 만들면 어떨까 하는 생각이 들었습니다
> design: 프로필 수정 페이지 레이아웃

- src/components/ArticleDetail.tsx
- src/components/Comment.tsx
- src/components/TabItem.tsx
- src/hooks/useArticleDetail.tsx
- src/pages/ArticleDetailPage.tsx
- src/pages/ArticleDetailPage/CommentInput.tsx
- src/pages/ArticleDetailPage/Comments.tsx
- src/stories/ArticleDetail.stories.tsx
- src/utils/getTimeStamp.ts
- close #108 
- 글 상세 페이지 레이아웃을 구현했습니다. 
- 게시판에서 특정 게시글을 선택 시, 해당 게시글의 상세 페이지로 이동합니다. 
- 자신이 작성한 게시글이 아닐 경우 수정, 삭제 버튼이 보이지 않습니다.
-
> design: 글 상세 페이지 레이아웃 구현

- src/App.tsx
- src/components/FormInput.tsx
- src/components/HeaderText.tsx
- src/hooks/useChangePassword.tsx
- src/pages/ChangePasswordPage.tsx
- src/pages/LoginPage.tsx
- src/pages/index.ts
- src/utils/Router.tsx
- close #124 
- **`pages/ChangePasswordPage.tsx`**
- 라우터 추가(`/password`), 페이지 인덱스 내보내기 추가
- FormInput 인풋 태그 내부 폰트를 bold에서 normal로 수정
- 임시 navbar에 '비번변경' 버튼 추가
- 내용 없는 `temp.tsx` 파일 삭제
- 모달 컴포넌트가 아직 개발되지 않아 자바스크립트 confirm으로 확인하게 하였습니다.
- 비밀번호와 비밀번호 확인 인풋에 각자 다른 상태를 부여하여 눈동자 아이콘이 개별적으로 동작하게 했습니다.
> feat: 비밀번호 변경 페이지 구현

- src/pages/LandingPage.tsx
- src/pages/LoadingPage.tsx
- src/pages/ProfileEditPage.tsx
- src/pages/ProtectedRouter.tsx
- src/pages/index.ts
- src/utils/Router.tsx
- close #148 
- Protected Router 컴포넌트를 만들었습니다
- 로딩 페이지를 추가했습니다
- 권한 없이 권한이 필요한 페이지에 들어가면 alert 메시지를 보여주고 로그인 페이지로 라우팅 시킵니다.
- alert가 뜨는 동안 흰화면인게 신경 쓰이네요. 좋은 방법이 있을까요?
- 로그인 페이지로 보낼때 replace 모드로 보냈는데 push로 보내는게 나을까요?
- 프로필 페이지에서 userId에 해당하는 유저의 정보를 받지 못했을때 에러 처리가 필요할 것 같습니다
> feat: protect Router 추가

- src/api/common/Post.ts
- src/components/Tab.tsx
- src/components/TabItem.tsx
- src/constants/Article.ts
- src/context/TabContext.tsx
- src/hooks/useFilteredArticles.tsx
- src/hooks/useScrollToTop.tsx
- src/pages/ArticleDetailPage.tsx
- src/pages/ArticlesPage.tsx
- src/pages/ArticlesPage/Articles.tsx
- src/pages/ArticlesPage/InfiniteScroll.tsx
- src/pages/ProfilePage.tsx
- src/pages/SearchPage.tsx
- src/stories/Tab.stories.tsx
- close #139 
1. 뜨거운/구독한 탭 기능을 구현했습니다.
2. 현재 클릭한 탭을 기억하는 기능을 추가했습니다.
- useInfiniteQuery를 사용해서 구독한 탭의 글들은 무한 스크롤로 가져오도록 구현했습니다.
- localStorage를 사용해서 현재 클릭한 탭을 저장합니다.
> feat: 뜨거운/구독한 탭 기능 구현

- src/api/common/Comment.ts
- src/api/common/Like.ts
- src/api/common/Post.ts
- src/api/saveArticle.ts
- src/components/CloseButton.tsx
- src/components/Comment.tsx
- src/components/SubButton.tsx
- src/hooks/useArticle.tsx
- src/hooks/useArticleDetail.tsx
- src/pages/ArticleDetailPage.tsx
- src/pages/ArticleDetailPage/CommentInput.tsx
- src/pages/ArticleDetailPage/Comments.tsx
- src/pages/NewArticlePage.tsx
- close #131 
게시글 상세 페이지를 구현했습니다. 
- 사용자가 좋아요 누른 글의 id와 현재 보고 있는 글의 id가 같을 시 좋아요 버튼은 활성화 되어 있습니다. 
- 버튼이 활성화 되어 있는 상태에서 버튼을 누르면 좋아요 취소가 작동합니다. 
- 버튼이 비활성화 되어 있는 상태에서 버튼을 누르면 좋아요가 작동합니다. 
- 이 모든 동작은 새로고침을 해야 정상적으로 동작합니다. 예를 들어, 좋아요 버튼을 연속으로 두 번 누르고 페이지를 이동했다가 다시 들어가면 좋아요 버튼이 여전히 활성화 되어 있습니다. 
- 이 부분에 대해 어제 하루종일 고민하였지만 역량부족으로 해결하지 못했습니다... 
- 좋아요 로직에 대해 많은 첨언 부탁드립니다...
- 게시물 페이지에서 글 상세 정보 변경 시 바로 반영하는 것이 가능한가요? 
- 상수분리나 리팩토링은 새로운 issue를 파서 진행하도록 하겠습니다!
> feat: 글 상세 페이지 구현

- src/constants/Home.ts
- src/pages/HomePage.tsx
- close #154 
- 홈페이지에서 인기뉴스와 최신뉴스를 각각 4개, 6개씩 불러와 보여줍니다. 
- '뜨거운 뉴스', '최신 뉴스'를 클릭하면 news 페이지로 이동합니다. 
인기탭으로 이동하는 건 추후에 하기로 했습니다.
> feat: 홈페이지 게시물 불러오기 구현

- src/components/BottomNavigation.tsx
- src/components/CloseButton.tsx
- src/constants/Messages.ts
- src/pages/HomePage.tsx
- src/pages/ProfileEditPage.tsx
- src/pages/ProfileEditPage/EditForm.tsx
- src/pages/ProfilePage.tsx
- tailwind.config.js
- close #178
- 권한없는 사용자가 네비게이션바의 프로필로고를 누르면 로그인 페이지로 라우팅 시키고 토스트메시지를 보여주었습니다
- 메인 페이지에서 검색 로고를 누르면 search로 이동하도록 했습니다
- 메인 페이지에서 마지막 게시글에 하단 네비게이션에 가려 보이지 않는 버그를 수정했습니다
- 프로필 수정 페이지에서 x버튼을 눌렀을때 모달을 띄워 경고 메시지를 보여주었습니다
- 프로필 수정페이지에서 이미지를 수정하는 기능을 제거했습니다
tailwindcss.config.js에 아래의 코드가 있었는데 이 코드 때문에 daisy가 자동으로 시스템 모드에 따라 라이트, 다크모드를 적용하는 것을
비활성화해서 일단은 주석으로 처리했습니다.
```js
darkMode: 'class',
```
- 추후 다크모드 토글버튼을 구현하면 활성화하면 될 것 같습니다
> Fix : 하단 네비게이션바 버그 수정 + 추가사항 수정

- src/components/SearchResultList.tsx
- src/components/Tab.tsx
- src/constants/Tab.ts
- src/hooks/useFilteredSearchResult.tsx
- src/hooks/useTab.tsx
- src/pages/ArticlesPage.tsx
- src/pages/ArticlesPage/Articles.tsx
- src/pages/HomePage.tsx
- src/pages/ProfilePage.tsx
- src/pages/SearchPage.tsx
- src/stories/Tab.stories.tsx
- src/type/User.ts
- close #171 
- 게시글 페이지에서 중복된 게시글들이 나오지 않도록 로직을 수정했습니다.
- 홈페이지에서 뜨거운 뉴스, 최신의 뉴스를 클릭하면 뉴스의 해당 탭으로 이동합니다.
- 탭을 상수화해서 useTab 훅으로 관리할 수 있도록 수정했습니다.
> refactor: 게시글 페이지 중복 처리 + 탭 상수화, useTab훅으로 관리

- src/constants/Tab.ts
- src/hooks/useArticles.tsx
- src/pages/ArticlesPage.tsx
- src/pages/ArticlesPage/RenderArticles.tsx
- src/pages/ArticlesPage/fetchArticles.ts
- src/pages/HomePage.tsx
- src/pages/ProfilePage.tsx
- src/pages/ProfilePage/LikeArticles.tsx
- src/pages/ProfilePage/UserArticles.tsx
- close #205 
- 게시글 페이지의 최신 탭에서 무한스크롤을 구현하기 위해 **fetchArticles** 함수와 **useInfiniteQuery**를 사용했습니다.
- 뜨거운 탭의 경우 무한 스크롤을 구현하기가 쉽지 않은 것 같습니다.
- 필터링을 해주어야 하는데, offset을 10개로 정하다보니 일부분만 받게 되고, 만약 총 10개가 보내지지 않았다면 계속 다른 글들을 보내도록 로직을 작성해야할 텐데 꽤 복잡한 것 같습니다.
- 맨 처음 데이터를 가져오는 것은 isFetching대신 isLoading을 사용하도록 했습니다. 
- 무한 스크롤의 경우 새로운 글들을 받아올 땐 isFetching을 사용했습니다.
> feat: 게시글 페이지 무한스크롤 구현

- src/constants/Tab.ts
- src/hooks/useArticleDetail.tsx
- src/pages/ArticlesPage.tsx
- src/pages/ArticlesPage/RenderArticles.tsx
- src/pages/ArticlesPage/RenderFollowingArticles.tsx
- src/pages/ArticlesPage/RenderHottestArticles.tsx
- src/pages/ArticlesPage/RenderNewestArticles.tsx
- src/pages/ArticlesPage/fetchArticles.ts
- src/pages/ArticlesPage/filterArticles.ts
- src/pages/ProfilePage.tsx
- close #225 
게시글 페이지의 탭들을 각각의 컴포넌트로 분리했습니다.
- RenderNewestArticles
- RenderHottestArticles
- RenderFollowingArticles
게시글 페이지에 로직이 모두 모여있어서 성능에 이슈가 생긴 것으로 보입니다(데이터 로딩 + context API를 사용하여 리렌더링 발생...). 각 컴포넌트로 분리하니 탭을 클릭할 때에 데이터 로딩이 시작됩니다.
로컬 환경에서 **51-55**점 정도 나오고 있습니다. 빌드해서 배포한 상태에서 테스트하면 점수가 좀 더 올라가지 않을까 생각합니다.
- 뜨거운 탭의 경우, 전체 게시글을 불러온 후에 정한 값보다 높은 값만 보여주는 식으로 되어 있는데, 뜨거운 탭 컴포넌트를 구현하는 방법이 고민이 됩니다.
- 홈페이지에서도 전체 게시글을 가져오기 때문에 크게 문제가 되지 않을지도 모르겠습니다.
- 앱의 높이가 달라지면 무한 스크롤이 제대로 동작하지 않습니다. 새 이슈를 만들어 이를 수정하도록 하겠습니다.
> refactor: 게시글 페이지 탭 별로 컴포넌트 분리

- src/components/BackButton.tsx
- src/pages/ProfilePage.tsx
- close #228 
- **로그아웃 버튼 삭제**
- **설정 버튼을 드롭다운 메뉴로 구현**
- 프로필 수정, 로그아웃, 테마 변경 의 세 가지 메뉴
- **[중요] 테마 변경 부분 콜백 함수 필요** 💥
- BackButton 공통 컴포넌트에서 색상이 color 속성으로 들어가 있는 부분을 className에 넣도록 수정했습니다.
- 기존 코드는 동작하지 않는 코드입니다.
- ProfilePage 페이지 컴포넌트에 다크모드와 라이트모드의 텍스트 색상을 넣어줬습니다.
<div align="center">
**[라이트 모드]**
**[다크 모드]**
</div>
**[중요] 테마 변경 부분 콜백 함수 필요** 💥
- 라이트/다크 모드 토글 함수가 만들어지면 드롭다운 메뉴의 '테마 변경' 메뉴의 콜백 함수로 넣어줘야 합니다.
- 드롭다운 메뉴 중 테마 변경 메뉴 삭제
> feat: 설정 버튼 드롭다운 메뉴 구현 및 사소한 수정

- src/constants/Messages.ts
- src/pages/ProfileEditPage/EditForm.tsx
- src/pages/ProfilePage.tsx
- close #236 
- 설정 버튼에 드롭다운 메뉴 '비밀번호 변경' 추가
- 설정 버튼의 드롭다운 메뉴 '로그아웃' 버튼 클릭 시, 모달 추가
- 프로필 수정 페이지에서 '비밀번호 변경' 버튼 삭제
**[드롭다운 메뉴 비밀번호 변경 버튼 추가]**
**[로그아웃 누를 시, 모달 추가]**
**[프로필 수정 페이지에서 비밀번호 변경 버튼 삭제]**
> feat: 설정 드롭다운 비밀번호 변경 버튼 추가 및 사소한 수정

- src/api/common/Post.ts
- src/components/TabItem.tsx
- src/constants/NewArticle.ts
- src/hooks/useArticle.tsx
- src/hooks/useEdit.tsx
- src/hooks/useLikeMutation.ts
- src/pages/ArticleDetailPage.tsx
- src/pages/ArticleEditPage.tsx
- src/pages/ArticleEditPage/ArticleEditForm.tsx
- src/pages/ArticleEditPage/ImagePreview.tsx
- src/pages/ArticlesPage/RenderArticles.tsx
- src/pages/ArticlesPage/RenderFollowingArticles.tsx
- src/pages/NewArticlePage.tsx
- src/pages/ProfilePage.tsx
- src/pages/ProfilePage/LikeArticles.tsx
- src/pages/ProfilePage/UserArticles.tsx
- close #232 
- 게시글 작성, 수정 페이지의 UI를 통일하였습니다.
- 게시글 수정 페이지에서 이미지를 업데이트할 때 발생하던 에러를 수정했습니다.
- 게시글 제목 prefix를 split해서 select의 option 값으로 설정해주도록 구현했습니다.
- 게시글 수정 페이지에서 이미지 업데이트
- 게시글 제목의 prefix가 없으면 에러 토스트를 띄우도록 수정
- 팔로우 탭 레이아웃 수정
> fix: 게시글 작성 / 게시글 수정 페이지의 이미지 업데이트 로직 수정

- src/components/DarkMode.tsx
- close #252 
- 사용자 컬러 모드를 받아 와서 바로 localStorage에 세팅합니다.
- 토글버튼을 누름에 따라 localStorage에 theme의 값이 변경됩니다. 
- 다크모드일 때는 햇님 아이콘, 라이트모드일 때는 달 아이콘입니다.
> fix: 다크모드 사용자 컬러모드로 초기 설정

- src/components/MainButton.tsx
- src/hooks/useArticleDetail.tsx
- src/pages/ArticleDetailPage.tsx
- src/pages/ArticleDetailPage/CommentInput.tsx
- src/pages/ArticleDetailPage/Comments.tsx
- src/pages/NewArticlePage.tsx
- close #255 
- 댓글 삭제 시 상세 페이지에 바로 반영 됩니다. 
- 하나뿐인 댓글 삭제 시 바로 '댓글이 없습니다'를 보여줍니다.
- 댓글 오류 메시지를 삭제했습니다.
- 댓글 작성 후 제출 중에는 작성버튼이 비활성화 됩니다.
- 글 작성 후 제출 중에는 작성버튼이 비활성화 됩니다.
> refactor: 댓글 삭제 시 상세 페이지 반영 + 댓글 오류 메시지 삭제 + 제출 중 버튼 비활성화

- src/pages/ArticleDetailPage.tsx
- src/pages/ArticlesPage.tsx
- src/pages/HomePage/HotArticles.tsx
- src/pages/NotificationPage/NoticeList.tsx
> refactor: 뜨거운뉴스 좋아요+토스트 수정

- src/constants/Messages.ts
- src/hooks/useFollowQuery.tsx
- src/pages/ProfilePage.tsx
- src/pages/SearchPage/UserListItem.tsx
- close #281 
- 검색 페이지에서 구독 버튼의 label 이름이 '팔로우'였던 것을 수정하였습니다.
- 본인의 프로필 페이지가 아닌 프로필 페이지에서 구독하기 버튼과 구독 취소하기 버튼을 추가했습니다.
- useFollowQuery 훅을 수정했습니다.
- 토스트 메시지 호출 부를 UI단에서 훅 내부로 옮겼습니다.
- onSettled에 쿼리 키를 추가하여 프로필 페이지에서 변경 사항이 바로 적용되도록 하였습니다.
- 메시지 상수 파일에 구독, 구독취소 관련 메시지를 추가하였습니다.
> feat: 프로필 페이지 구독, 구독취소 버튼 구현
